# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::591131890162:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1OXTTNBV2MY1U
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::591131890162:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-09T16:12:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1823"
  uid: 5bf625fa-f12c-4f16-a4eb-a2c316a5d69b
